services:
  backend:
    build: backend
    depends_on:
      - postgres
      - authorizor
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: conference_app
      PGUSER: conference_app_user
      PGPASSWORD: banana9342
      PGAPPNAME: conference-go
      PORT: 8080
      AUTH_API_URL: http://authorizor:8082/api
    ports:
      - "8080:8080"
    command: npm run dev

  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: conference_app_user
      POSTGRES_PASSWORD: banana9342
      POSTGRES_DB: conference_app

  web:
    build: frontend
    depends_on:
      - gateway
    environment:
      REACT_APP_API_URL: http://localhost:80/api
    ports:
     - "3000:3000"
    command: npm run start

  gateway:
    build: gateway
    ports:
      - "80:80"
    depends_on:
      - authorizor
      - backend

  authorizor:
    build: authorizor
    ports:
      - "8082:8082"
    depends_on:
      - authdb
    command: npm run dev
    environment:
      PGHOST: authdb
      PGPORT: 5432
      PGDATABASE: conference_authentication
      PGUSER: conference_auth_user
      PGPASSWORD: banana9342
      PGAPPNAME: conference-go-auth
      PORT: 8082
      JWT_SECRET: 3asdf42sdw1xljk*m^lkasjmdflkj290=113x7yosxs7923dckl3exq

  authdb:
    image: postgres:10.4
    ports:
      - "35434:5432"
    environment:
      POSTGRES_USER: conference_auth_user
      POSTGRES_PASSWORD: banana9342
      POSTGRES_DB: conference_authentication